MONGODB_CONNECTION_STRING="mongodb://airlinedb_user:8649OV57IGR3Y1JS@ec2-43-205-133-199.ap-south-1.compute.amazonaws.com/admin?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.2.3"
DATABASE_GST="gstservice"
COLLECTION_GST_INPUT_2B="two-b-flat"
DATABASE_FUZZY="fuzzy_match"
COLLECTION_FUZZY_OUTPUT="data_output"